name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set Environment Variable for SMTP_PASS
      - name: Set Environment Variable for SMTP_PASS
        run: echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> $GITHUB_ENV

      # Run PHP Script to check if SMTP_PASS is set
      - name: Run PHP Script to verify SMTP_PASS
        run: |
          if [[ -z "$SMTP_PASS" ]]; then
            echo "SMTP_PASS is not set."
          else
            echo "SMTP_PASS is set successfully (but not printing for security)."
          fi

      # FTP Deploy
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.sennevisser.me
          username: u540587252
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/sennevisser.me/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/.idea*
            **/.idea*/**
