name: FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set Environment Variable for SMTP_PASS
      - name: Set Environment Variable for SMTP_PASS
        run: echo "SMTP_PASS=${{ secrets.SMTP_PASS }}" >> $GITHUB_ENV

      # Print Environment Variables for Debugging
      - name: Print Environment Variables
        run: env

      # Run PHP Script to check SMTP_PASS
      - name: Run PHP Script
        run: php index.php

      # FTP Deploy
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.sennevisser.me
          username: u540587252
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/sennevisser.me/public_html/
          exclude: |
            **/.git*
            **/.git*/**
            **/.idea*
            **/.idea*/**